application: gae-php-tutorial
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /helloworld.*
  script: helloworld.php

- url: /hellouser.*
  script: hellouser.php

- url: /sign.*
  script: webform.php

- url: /.*
  script: index.php
